# Generated by Django 2.1.13 on 2019-10-30 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('total_payment', models.FloatField()),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=120)),
                ('SDT', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ExportStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_export_list', models.CharField(max_length=150)),
                ('export_date', models.DateTimeField(blank=True, null=True)),
                ('total_export', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_import_list', models.CharField(max_length=150)),
                ('import_date', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('total_import', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportStorage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ExportStorage')),
            ],
        ),
        migrations.CreateModel(
            name='Item_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importStorage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ImportStorage')),
            ],
        ),
        migrations.CreateModel(
            name='Item_in_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Item_in_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=5)),
                ('Category', models.TextField(choices=[('Footwear', 'footwear'), ('Apparel', 'apparel'), ('Accessories', 'accessories')])),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id_shop', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name_shop', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_storage', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item_in_storage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='item_in_storage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Storage'),
        ),
        migrations.AddField(
            model_name='item_in_bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='item_import',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='item_export',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='importstorage',
            name='storage_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Storage'),
        ),
        migrations.AddField(
            model_name='exportstorage',
            name='storage_export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Storage'),
        ),
    ]
